import Logarithm.ScaledArithmetic

/-! Integer clearing for rational-centre logarithmic jets

The inherited coefficient-clearing theorem lands in the Gaussian integers.
Here the same elementary polynomial argument is carried out over `ℤ` itself.
This keeps subsequent determinant norms in the field generated by the real
algebraic base; no auxiliary square root of minus one is introduced.
-/

namespace OAI.AlgebraicLog.IntegerClearing

noncomputable section
open scoped BigOperators
open PiExponent PiExponent.InterpolationMatrix

theorem lcm_mul_log_coeff_int (T k : ℕ) (hk : k ≤ T) :
    (Nat.lcmUpto T : ℂ) * PowerSeries.coeff k (PowerSeries.log ℂ) ∈
      (Int.castRingHom ℂ).range := by
  by_cases hk0 : k = 0
  · simp [hk0]
  obtain ⟨n, hn⟩ := Arithmetic.dvd_lcmUpto_of_pos_le (Nat.pos_of_ne_zero hk0) hk
  refine ⟨(-1 : ℤ) ^ (k + 1) * (n : ℤ), ?_⟩
  rw [PowerSeries.coeff_log, ite_eq_right hk0, hn]
  have hkC : (k : ℂ) ≠ 0 := by exact_mod_cast hk0
  simp only [map_mul, map_pow, map_neg, map_one, map_natCast, map_div₀, Nat.cast_mul]
  field_simp

theorem cleared_log_trunc_mem (T : ℕ) :
    Polynomial.C (Nat.lcmUpto T : ℂ) * PowerSeries.trunc T (PowerSeries.log ℂ) ∈
      (Polynomial.mapRingHom (Int.castRingHom ℂ)).range := by
  apply (Polynomial.mem_map_range (Int.castRingHom ℂ)).mpr
  intro k
  rw [Polynomial.coeff_C_mul, PowerSeries.coeff_trunc]
  split_ifs with hk
  · exact lcm_mul_log_coeff_int T k hk.le
  · simp

theorem int_C_mem (z : ℤ) :
    Polynomial.C (z : ℂ) ∈ (Polynomial.mapRingHom (Int.castRingHom ℂ)).range := by
  exact ⟨Polynomial.C z, by simp⟩

theorem cleared_shifted_log_trunc_mem (T q : ℕ) (z : ℤ) :
    Polynomial.C (Nat.lcmUpto T : ℂ) *
      (Polynomial.C (z : ℂ) + Polynomial.C (q : ℂ) *
        PowerSeries.trunc T (PowerSeries.log ℂ)) ∈
      (Polynomial.mapRingHom (Int.castRingHom ℂ)).range := by
  let S := (Polynomial.mapRingHom (Int.castRingHom ℂ)).range
  have hL : Polynomial.C (Nat.lcmUpto T : ℂ) ∈ S := by simp
  have hq : Polynomial.C (q : ℂ) ∈ S := by simp
  have hlog := cleared_log_trunc_mem T
  have h := S.add_mem (S.mul_mem hL (int_C_mem z)) (S.mul_mem hq hlog)
  convert h using 1
  ring

theorem cleared_polynomial_power_mem (L e d : ℕ) (f : Polynomial ℂ) (hd : d ≤ e)
    (hf : Polynomial.C (L : ℂ) * f ∈
      (Polynomial.mapRingHom (Int.castRingHom ℂ)).range) :
    Polynomial.C ((L : ℂ) ^ e) * f ^ d ∈
      (Polynomial.mapRingHom (Int.castRingHom ℂ)).range := by
  let S := (Polynomial.mapRingHom (Int.castRingHom ℂ)).range
  have hL : Polynomial.C (L : ℂ) ∈ S := by simp
  have h := S.mul_mem (S.pow_mem hL (e - d)) (S.pow_mem hf d)
  have he : e = (e - d) + d := (Nat.sub_add_cancel hd).symm
  rw [he, map_pow, pow_add]
  simpa only [mul_pow, mul_assoc] using h

theorem cleared_polynomial_product_mem {ι : Type*} (s : Finset ι)
    (L e d : ι → ℕ) (f : ι → Polynomial ℂ) (hd : ∀ i ∈ s, d i ≤ e i)
    (hf : ∀ i ∈ s, Polynomial.C (L i : ℂ) * f i ∈
      (Polynomial.mapRingHom (Int.castRingHom ℂ)).range) :
    Polynomial.C (∏ i ∈ s, (L i : ℂ) ^ e i) * (∏ i ∈ s, f i ^ d i) ∈
      (Polynomial.mapRingHom (Int.castRingHom ℂ)).range := by
  let S := (Polynomial.mapRingHom (Int.castRingHom ℂ)).range
  have h := S.prod_mem (fun i hi => cleared_polynomial_power_mem (L i) (e i) (d i)
    (f i) (hd i hi) (hf i hi))
  simpa only [← Finset.prod_mul_distrib, map_prod] using h

theorem common_denominator_coeff_int {ι : Type*} (s : Finset ι)
    (L e d : ι → ℕ) (f : ι → Polynomial ℂ) (P : Polynomial ℤ)
    (hd : ∀ i ∈ s, d i ≤ e i)
    (hf : ∀ i ∈ s, Polynomial.C (L i : ℂ) * f i ∈
      (Polynomial.mapRingHom (Int.castRingHom ℂ)).range) (k : ℕ) :
    (∏ i ∈ s, (L i : ℂ) ^ e i) *
      (P.map (Int.castRingHom ℂ) * ∏ i ∈ s, f i ^ d i).coeff k ∈
      (Int.castRingHom ℂ).range := by
  let S := (Polynomial.mapRingHom (Int.castRingHom ℂ)).range
  have hP : P.map (Int.castRingHom ℂ) ∈ S := ⟨P, rfl⟩
  have h := S.mul_mem hP (cleared_polynomial_product_mem s L e d f hd hf)
  have he : P.map (Int.castRingHom ℂ) *
      (Polynomial.C (∏ i ∈ s, (L i : ℂ) ^ e i) * ∏ i ∈ s, f i ^ d i) =
      Polynomial.C (∏ i ∈ s, (L i : ℂ) ^ e i) *
        (P.map (Int.castRingHom ℂ) * ∏ i ∈ s, f i ^ d i) := by ring
  rw [he] at h
  have hc := (Polynomial.mem_map_range (Int.castRingHom ℂ)).mp h k
  simpa only [Polynomial.coeff_C_mul] using hc

theorem shifted_truncation_product_coeff_int {ι : Type*} (s : Finset ι)
    (T q e d : ι → ℕ) (z : ι → ℤ) (P : Polynomial ℤ)
    (hd : ∀ i ∈ s, d i ≤ e i) (k : ℕ) :
    (∏ i ∈ s, (Nat.lcmUpto (T i) : ℂ) ^ e i) *
      (P.map (Int.castRingHom ℂ) * ∏ i ∈ s,
        (Polynomial.C (z i : ℂ) + Polynomial.C (q i : ℂ) *
          PowerSeries.trunc (T i) (PowerSeries.log ℂ)) ^ d i).coeff k ∈
      (Int.castRingHom ℂ).range := by
  exact common_denominator_coeff_int s (fun i => Nat.lcmUpto (T i)) e d _ P hd
    (fun i hi => cleared_shifted_log_trunc_mem (T i) (q i) (z i)) k

/-- Rational additive centres give integer cleared coefficients. The row factor
`q^(-β)` is retained, which is essential for the final quadratic exponent. -/
theorem entry_truncatedLog_cleared_int {m : ℕ}
    (T q e : Fin m → ℕ) (p : Fin m → ℤ) (hq : ∀ i, q i ≠ 0)
    (j s h : ℕ) (β γ : Fin m → ℕ) (hγ : ∀ i, γ i ≤ e i) :
    (∏ i, (Nat.lcmUpto (T i) : ℂ) ^ e i) *
      (∏ i, (q i : ℂ) ^ γ i) / (∏ i, (q i : ℂ) ^ β i) *
      entry (fun i => (p i : ℂ) / (q i : ℂ))
        (fun i => truncatedLog (T i)) j s β h γ ∈
      (Int.castRingHom ℂ).range := by
  classical
  by_cases hβγ : ∀ i, β i ≤ γ i
  swap
  · rw [entry_eq_zero_of_not_le _ _ _ _ _ _ _ hβγ, mul_zero]
    exact (Int.castRingHom ℂ).range.zero_mem
  have hqC : ∀ i, (q i : ℂ) ≠ 0 := by
    intro i
    exact_mod_cast hq i
  have hratio : (∏ i, (q i : ℂ) ^ γ i) / (∏ i, (q i : ℂ) ^ β i) =
      ∏ i, (q i : ℂ) ^ (γ i - β i) := by
    rw [← Finset.prod_div_distrib]
    apply Finset.prod_congr rfl
    intro i hi
    simpa only [div_eq_mul_inv] using (pow_sub₀ (q i : ℂ) (hqC i) (hβγ i)).symm
  let z : Fin m → ℤ := fun i => (j : ℤ) * p i
  have hz (i : Fin m) : Polynomial.C (q i : ℂ) *
      (Polynomial.C ((j : ℂ) * ((p i : ℂ) / (q i : ℂ))) +
        truncatedLog (T i)) =
      Polynomial.C (z i : ℂ) + Polynomial.C (q i : ℂ) *
        PowerSeries.trunc (T i) (PowerSeries.log ℂ) := by
    rw [mul_add, ← map_mul]
    congr 1
    apply congrArg Polynomial.C
    simp only [z, Int.cast_mul, Int.cast_natCast]
    field_simp [hqC i]
  have hclear := shifted_truncation_product_coeff_int Finset.univ
    T q e (fun i => γ i - β i) z ((1 + Polynomial.X) ^ h)
    (fun i hi => (Nat.sub_le (γ i) (β i)).trans (hγ i)) s
  have hP : (((1 + Polynomial.X) ^ h : Polynomial ℤ).map (Int.castRingHom ℂ)) =
      (1 + Polynomial.X) ^ h := by simp
  simp only [hP] at hclear
  have hchoose : (∏ i, ((γ i).choose (β i) : ℂ)) ∈ (Int.castRingHom ℂ).range := by
    apply (Int.castRingHom ℂ).range.prod_mem
    intro i hi
    exact ⟨((γ i).choose (β i) : ℤ), by simp⟩
  have hscalar := scalar_product_mul_coeff (fun i => (q i : ℂ)) (fun i => γ i - β i)
    ((1 + Polynomial.X) ^ h)
    (fun i => Polynomial.C ((j : ℂ) * ((p i : ℂ) / (q i : ℂ))) +
      truncatedLog (T i)) s
  simp_rw [hz] at hscalar
  rw [mul_div_assoc, hratio, entry_eq_binomial_product]
  have he := (Int.castRingHom ℂ).range.mul_mem hchoose hclear
  rw [← hscalar] at he
  convert he using 1
  ring

end
end OAI.AlgebraicLog.IntegerClearing
